version: '3'

services:
  permissions:
    image: alpine:latest
    volumes:
      - "agent-vol:/home/jenkins/"
    command: chown -R 1000:1000 /home/jenkins/
  worker:
    build: ./worker
    image: worker:latest
    hostname: worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "agent-vol:/home/jenkins/"
    depends_on:
      permissions:
        condition: service_completed_successfully
  master:
    build: ./master
    image: master:latest
    hostname: master
    restart: on-failure
    volumes:
      - "master-vol:/var/jenkins_home/"
    ports:
      - "50000:50000"
    environment:
      - JENKINS_PASS=test
      - JAVA_OPTS=-Xmx2048m -Djenkins.install.runSetupWizard=false
    links:
      - worker:worker
  nginx:
    image: nginx:latest
    volumes:
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf/jenkins.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    links:
      - master:master

volumes:
  master-vol:
    driver: local
  agent-vol:
    driver: local
